output_root: output


data_ingestion:
  root_dir: output/data_ingestion
  source_URL: https://drive.google.com/file/d/10xqSnMgeJwvsf2wHt8rQBx3Ixh5v52os/view?usp=sharing
  local_data_file: output/data_ingestion/fruitsdata.zip
  unzip_dir: output/data_ingestion



prepare_base_model:
  root_dir: output/prepare_base_model
  base_model_path: output/prepare_base_model/base_model.h5
  updated_base_model_path: output/prepare_base_model/base_model_updated.h5




prepare_callbacks:
  root_dir: output/prepare_callbacks
  tensorboard_root_log_dir: output/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: output/prepare_callbacks/checkpoint_dir/model.h5




training:
  root_dir: output/training
  trained_model_path: output/training/model.h5


